<Project Sdk="Microsoft.NET.Sdk" TreatAsLocalProperty="PublishAot">
  <PropertyGroup>
    <TargetFramework />
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <PublishAot>false</PublishAot>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>The Light.PortableResults package implements the core functionality: Results, Errors, Metadata, Functional Extensions, and serialization support for various formats like HTTP and CloudEvents. Compatible with Native AOT. Check out the integration packages Light.PortableResults.AspNetCore.MinimalApis or Light.PortableResults.AspNetCore.Mvc.</Description>
    <PackageReleaseNotes></PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.HashCode" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Primitives" />
    <PackageReference Include="Polyfill" PrivateAssets="all" />
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Ulid" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../THIRD-PARTY-NOTICES.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
