using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace Light.PortableResults.Validation.OpenApi.SourceGeneration;

internal static class ValidatorOpenApiEmitter
{
    public static string Emit(ValidatorModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using Light.PortableResults.AspNetCore.OpenApi;");
        builder.AppendLine("using Light.PortableResults.Validation.OpenApi;");
        builder.AppendLine("using Microsoft.OpenApi;");
        builder.AppendLine();

        if (model.NamespaceName is not null)
        {
            builder.Append("namespace ").Append(model.NamespaceName).AppendLine();
            builder.AppendLine("{");
        }

        var indent = model.NamespaceName is null ? "" : "    ";
        builder.Append(indent)
           .Append(model.Accessibility)
           .Append(" partial class ")
           .Append(model.ClassName)
           .Append(" : IPortableValidationOpenApiContract")
           .AppendLine();
        builder.Append(indent).AppendLine("{");
        builder.Append(indent).AppendLine(
            "    public static void ConfigurePortableValidationOpenApi(PortableValidationProblemOpenApiBuilder builder)"
        );
        builder.Append(indent).AppendLine("    {");
        builder.Append(indent).AppendLine("        if (builder is null)");
        builder.Append(indent).AppendLine("        {");
        builder.Append(indent).AppendLine("            throw new ArgumentNullException(nameof(builder));");
        builder.Append(indent).AppendLine("        }");
        builder.AppendLine();

        EmitSchemaConfiguration(builder, model, indent + "        ");
        EmitExamples(builder, model, indent + "        ");

        if (model.AllowUnknownErrorCodes)
        {
            builder.Append(indent).AppendLine("        builder.AllowUnknownErrorCodes();");
        }

        builder.Append(indent).AppendLine("    }");
        builder.Append(indent).AppendLine("}");

        if (model.NamespaceName is not null)
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void EmitSchemaConfiguration(StringBuilder builder, ValidatorModel model, string indent)
    {
        var registeredCodes = model
           .Rules
           .Where(
                static rule => rule.Shape == RuleMetadataShape.Registered &&
                               rule.MetadataSchemaProperties.Length == 0
            )
           .Select(static rule => rule.Code)
           .Concat(model.Hints.Where(static hint => hint.MetadataTypeName is null).Select(static hint => hint.Code))
           .Distinct(StringComparer.Ordinal)
           .OrderBy(static code => code, StringComparer.Ordinal)
           .ToArray();
        if (registeredCodes.Length > 0)
        {
            builder.Append(indent).Append("builder.WithErrorCodes(");
            for (var i = 0; i < registeredCodes.Length; i++)
            {
                if (i > 0)
                {
                    builder.Append(", ");
                }

                builder.Append(ToStringLiteral(registeredCodes[i]));
            }

            builder.AppendLine(");");
        }

        foreach (var hint in model.Hints.Where(static hint => hint.MetadataTypeName is not null))
        {
            builder
               .Append(indent)
               .Append("builder.WithErrorMetadata<")
               .Append(hint.MetadataTypeName)
               .Append(">(")
               .Append(ToStringLiteral(hint.Code))
               .AppendLine(");");
        }

        foreach (var rule in model.Rules
                    .Where(
                         static rule => rule.Shape == RuleMetadataShape.Registered &&
                                        rule.MetadataSchemaProperties.Length > 0
                     )
                    .Distinct(InlineSchemaRuleComparer.Instance)
                    .OrderBy(static rule => rule.Code, StringComparer.Ordinal))
        {
            EmitInlineSchemaConfiguration(builder, rule, indent);
        }

        foreach (var rule in model.Rules
                    .Where(static rule => rule.Shape != RuleMetadataShape.Registered)
                    .Distinct(RuleSchemaKeyComparer.Instance)
                    .OrderBy(static rule => rule.Code, StringComparer.Ordinal)
                    .ThenBy(static rule => rule.TypedValueTypeName, StringComparer.Ordinal))
        {
            var helperName = GetTypedHelperName(rule);
            if (helperName is null || rule.TypedValueTypeName is null)
            {
                continue;
            }

            builder
               .Append(indent)
               .Append("builder.")
               .Append(helperName)
               .Append('<')
               .Append(rule.TypedValueTypeName)
               .AppendLine(">();");
        }

        if (registeredCodes.Length > 0 ||
            model.Hints.Length > 0 ||
            model.Rules.Any(static rule => rule.Shape != RuleMetadataShape.Registered) ||
            model.Rules.Any(
                static rule => rule.Shape == RuleMetadataShape.Registered &&
                               rule.MetadataSchemaProperties.Length > 0
            ))
        {
            builder.AppendLine();
        }
    }

    private static void EmitInlineSchemaConfiguration(StringBuilder builder, RuleCallModel rule, string indent)
    {
        builder
           .Append(indent)
           .Append("builder.WithErrorMetadata(")
           .Append(ToStringLiteral(rule.Code))
           .AppendLine(", _ => new OpenApiSchema");
        builder.Append(indent).AppendLine("{");
        builder.Append(indent).AppendLine("    Type = JsonSchemaType.Object,");
        builder
           .Append(indent)
           .AppendLine("    Properties = new Dictionary<string, IOpenApiSchema>(StringComparer.Ordinal)");
        builder.Append(indent).AppendLine("    {");

        foreach (var property in rule.MetadataSchemaProperties.OrderBy(
                     static property => property.Key,
                     StringComparer.Ordinal
                 ))
        {
            builder
               .Append(indent)
               .Append("        [")
               .Append(ToStringLiteral(property.Key))
               .Append("] = PortableOpenApiSchemaTypeMapper.Map<")
               .Append(property.TypeName)
               .AppendLine(">(),");
        }

        builder.Append(indent).AppendLine("    },");
        builder.Append(indent).Append("    Required = new HashSet<string>(StringComparer.Ordinal) { ");
        for (var i = 0; i < rule.MetadataSchemaProperties.Length; i++)
        {
            if (i > 0)
            {
                builder.Append(", ");
            }

            builder.Append(ToStringLiteral(rule.MetadataSchemaProperties[i].Key));
        }

        builder.AppendLine(" }");
        builder
           .Append(indent)
           .Append("}, ")
           .Append(ToStringLiteral(rule.Code + "Metadata"))
           .AppendLine(");");
    }

    private static void EmitExamples(StringBuilder builder, ValidatorModel model, string indent)
    {
        foreach (var rule in model.Rules)
        {
            if (rule.MetadataValues.Any(static metadata => !metadata.HasConstantValue))
            {
                continue;
            }

            builder.Append(indent)
               .Append("builder.WithErrorExample(")
               .Append(ToStringLiteral(rule.Code))
               .Append(", ")
               .Append(rule.Target is null ? "null" : ToStringLiteral(rule.Target));

            if (rule.MetadataValues.Length > 0)
            {
                builder.Append(", ");
                EmitMetadataDictionary(builder, rule.MetadataValues);
            }

            builder.AppendLine(");");
        }

        if (model.Rules.Length > 0)
        {
            builder.AppendLine();
        }
    }

    private static void EmitMetadataDictionary(StringBuilder builder, IEnumerable<MetadataValueModel> metadataValues)
    {
        builder.Append("new Dictionary<string, object?>(StringComparer.Ordinal) { ");
        var isFirst = true;
        foreach (var metadataValue in metadataValues)
        {
            if (!isFirst)
            {
                builder.Append(", ");
            }

            builder.Append('[')
               .Append(ToStringLiteral(metadataValue.Key))
               .Append("] = ")
               .Append(ToLiteral(metadataValue.Value));
            isFirst = false;
        }

        builder.Append(" }");
    }

    private static string? GetTypedHelperName(RuleCallModel rule) =>
        rule.Code switch
        {
            "EqualTo" => "WithEqualToError",
            "NotEqualTo" => "WithNotEqualToError",
            "GreaterThan" => "WithGreaterThanError",
            "GreaterThanOrEqualTo" => "WithGreaterThanOrEqualToError",
            "LessThan" => "WithLessThanError",
            "LessThanOrEqualTo" => "WithLessThanOrEqualToError",
            "InRange" => "WithInRangeError",
            "NotInRange" => "WithNotInRangeError",
            "ExclusiveRange" => "WithExclusiveRangeError",
            _ => null
        };

    private static string ToLiteral(object? value) =>
        value switch
        {
            null => "null",
            string stringValue => ToStringLiteral(stringValue),
            char charValue => "'" + EscapeChar(charValue) + "'",
            bool boolValue => boolValue ? "true" : "false",
            byte byteValue => byteValue.ToString(CultureInfo.InvariantCulture),
            sbyte sbyteValue => sbyteValue.ToString(CultureInfo.InvariantCulture),
            short shortValue => shortValue.ToString(CultureInfo.InvariantCulture),
            ushort ushortValue => ushortValue.ToString(CultureInfo.InvariantCulture),
            int intValue => intValue.ToString(CultureInfo.InvariantCulture),
            uint uintValue => uintValue.ToString(CultureInfo.InvariantCulture) + "U",
            long longValue => longValue.ToString(CultureInfo.InvariantCulture) + "L",
            ulong ulongValue => ulongValue.ToString(CultureInfo.InvariantCulture) + "UL",
            float floatValue => floatValue.ToString("R", CultureInfo.InvariantCulture) + "F",
            double doubleValue => doubleValue.ToString("R", CultureInfo.InvariantCulture) + "D",
            decimal decimalValue => decimalValue.ToString(CultureInfo.InvariantCulture) + "M",
            _ => ToStringLiteral(value.ToString() ?? string.Empty)
        };

    private static string ToStringLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var c in value)
        {
            builder.Append(EscapeChar(c));
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static string EscapeChar(char value) =>
        value switch
        {
            '\\' => @"\\",
            '"' => "\\\"",
            '\'' => "\\'",
            '\0' => "\\0",
            '\a' => "\\a",
            '\b' => "\\b",
            '\f' => "\\f",
            '\n' => "\\n",
            '\r' => "\\r",
            '\t' => "\\t",
            '\v' => "\\v",
            _ => char.IsControl(value) ?
                "\\u" + ((int) value).ToString("x4", CultureInfo.InvariantCulture) :
                value.ToString()
        };
}
