using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace Light.PortableResults.Validation.OpenApi.SourceGeneration;

internal static class ValidatorOpenApiEmitter
{
    public static string Emit(ValidatorModel model)
    {
        var writer = new CodeWriter()
           .WriteLine("// <auto-generated />")
           .WriteLine("#nullable enable")
           .WriteLine("using System;")
           .WriteLine("using System.Collections.Generic;")
           .WriteLine("using Light.PortableResults.AspNetCore.OpenApi;")
           .WriteLine("using Light.PortableResults.Validation.OpenApi;")
           .WriteLine("using Microsoft.OpenApi;")
           .WriteLine();

        if (model.NamespaceName is not null)
        {
            writer
               .Write("namespace ")
               .WriteLine(model.NamespaceName)
               .OpenBrace();
        }

        writer
           .Write(model.Accessibility)
           .Write(" partial class ")
           .Write(model.ClassName)
           .WriteLine(" : IPortableValidationOpenApiContract")
           .OpenBrace()
           .WriteLine(
                "public static void ConfigurePortableValidationOpenApi(PortableValidationProblemOpenApiBuilder builder)"
            )
           .OpenBrace()
           .WriteLine("if (builder is null)")
           .OpenBrace()
           .WriteLine("throw new ArgumentNullException(nameof(builder));")
           .CloseBrace()
           .WriteLine();

        EmitSchemaConfiguration(writer, model);
        EmitExamples(writer, model);

        if (model.AllowUnknownErrorCodes)
        {
            writer.WriteLine("builder.AllowUnknownErrorCodes();");
        }

        writer.CloseBrace().CloseBrace();

        if (model.NamespaceName is not null)
        {
            writer.CloseBrace();
        }

        return writer.ToString();
    }

    private static CodeWriter EmitSchemaConfiguration(CodeWriter writer, ValidatorModel model)
    {
        var schemaCodes = new HashSet<string>(
            model.Rules.Select(static rule => rule.Code).Concat(model.Hints.Select(static hint => hint.Code)),
            StringComparer.Ordinal
        );
        var registeredCodes = model
           .Rules
           .Where(
                static rule => rule.Shape == RuleMetadataShape.Registered &&
                               rule.MetadataSchemaProperties.Length == 0
            )
           .Select(static rule => rule.Code)
           .Concat(
                model.Hints
                   .Where(
                        static hint => hint.MetadataTypeName is null &&
                                       hint.MetadataSchemaProperties.Length == 0
                    )
                   .Select(static hint => hint.Code)
           )
           .Concat(
                model.Examples
                   .Where(example => !schemaCodes.Contains(example.Code))
                   .Select(static example => example.Code)
            )
           .Distinct(StringComparer.Ordinal)
           .OrderBy(static code => code, StringComparer.Ordinal)
           .ToArray();
        if (registeredCodes.Length > 0)
        {
            writer
               .Write("builder.WithErrorCodes(")
               .Write(string.Join(", ", registeredCodes.Select(ToStringLiteral)))
               .WriteLine(");");
        }

        foreach (var hint in model.Hints
                    .Where(static hint => hint.MetadataTypeName is not null)
                    .GroupBy(static hint => new { hint.Code, hint.MetadataTypeName })
                    .Select(static group => group.First())
                    .OrderBy(static hint => hint.Code, StringComparer.Ordinal)
                    .ThenBy(static hint => hint.MetadataTypeName, StringComparer.Ordinal))
        {
            writer
               .Write("builder.WithErrorMetadata<")
               .Write(hint.MetadataTypeName!)
               .Write(">(")
               .Write(ToStringLiteral(hint.Code))
               .WriteLine(");");
        }

        foreach (var hint in model.Hints
                    .Where(static hint => hint.MetadataSchemaProperties.Length > 0)
                    .GroupBy(static hint => hint.Code, StringComparer.Ordinal)
                    .Select(static group => group.First())
                    .OrderBy(static hint => hint.Code, StringComparer.Ordinal))
        {
            EmitInlineSchemaConfiguration(
                writer,
                hint.Code,
                hint.MetadataSchemaProperties,
                hint.Code + "Metadata"
            );
        }

        foreach (var rule in model.Rules
                    .Where(
                         static rule => rule.Shape == RuleMetadataShape.Registered &&
                                        rule.MetadataSchemaProperties.Length > 0
                     )
                    .Distinct(InlineSchemaRuleComparer.Instance)
                    .OrderBy(static rule => rule.Code, StringComparer.Ordinal))
        {
            EmitInlineSchemaConfiguration(writer, rule);
        }

        foreach (var rule in model.Rules
                    .Where(static rule => rule.Shape != RuleMetadataShape.Registered)
                    .Distinct(RuleSchemaKeyComparer.Instance)
                    .OrderBy(static rule => rule.Code, StringComparer.Ordinal)
                    .ThenBy(static rule => rule.TypedValueTypeName, StringComparer.Ordinal))
        {
            var helperName = GetTypedHelperName(rule);
            if (helperName is null || rule.TypedValueTypeName is null)
            {
                continue;
            }

            writer
               .Write("builder.")
               .Write(helperName)
               .Write('<')
               .Write(rule.TypedValueTypeName)
               .WriteLine(">();");
        }

        if (registeredCodes.Length > 0 ||
            model.Hints.Length > 0 ||
            model.Examples.Length > 0 ||
            model.Rules.Any(static rule => rule.Shape != RuleMetadataShape.Registered) ||
            model.Rules.Any(
                static rule => rule.Shape == RuleMetadataShape.Registered &&
                               rule.MetadataSchemaProperties.Length > 0
            ))
        {
            writer.WriteLine();
        }

        return writer;
    }

    private static CodeWriter EmitInlineSchemaConfiguration(CodeWriter writer, RuleCallModel rule)
    {
        return EmitInlineSchemaConfiguration(
            writer,
            rule.Code,
            rule.MetadataSchemaProperties,
            rule.Code + "Metadata"
        );
    }

    private static CodeWriter EmitInlineSchemaConfiguration(
        CodeWriter writer,
        string code,
        IEnumerable<MetadataSchemaPropertyModel> metadataSchemaProperties,
        string schemaId
    )
    {
        var properties = metadataSchemaProperties
           .OrderBy(static property => property.Key, StringComparer.Ordinal)
           .ToArray();
        var requiredKeys = string.Join(", ", properties.Select(static property => ToStringLiteral(property.Key)));

        writer
           .Write("builder.WithErrorMetadata(")
           .Write(ToStringLiteral(code))
           .WriteLine(", _ => new OpenApiSchema")
           .WriteLine("{")
           .IncreaseIndent()
           .WriteLine("Type = JsonSchemaType.Object,")
           .WriteLine("Properties = new Dictionary<string, IOpenApiSchema>(StringComparer.Ordinal)")
           .WriteLine("{")
           .IncreaseIndent();

        foreach (var property in properties)
        {
            writer
               .Write("[")
               .Write(ToStringLiteral(property.Key))
               .Write("] = PortableOpenApiSchemaTypeMapper.Map<")
               .Write(property.TypeName)
               .WriteLine(">(),");
        }

        return writer
           .DecreaseIndent()
           .WriteLine("},")
           .Write("Required = new HashSet<string>(StringComparer.Ordinal) { ")
           .Write(requiredKeys)
           .WriteLine(" }")
           .DecreaseIndent()
           .Write("}, ")
           .Write(ToStringLiteral(schemaId))
           .WriteLine(");");
    }

    private static CodeWriter EmitExamples(CodeWriter writer, ValidatorModel model)
    {
        foreach (var rule in model.Rules)
        {
            var canEmitMetadata = rule.MetadataValues.All(static metadata => metadata.HasConstantValue);

            writer
               .Write("builder.WithErrorExample(")
               .Write(ToStringLiteral(rule.Code))
               .Write(", ")
               .Write(rule.Target is null ? "null" : ToStringLiteral(rule.Target))
               .Write(", ")
               .Write(rule.Message is null ? "null" : ToStringLiteral(rule.Message));

            if (canEmitMetadata && rule.MetadataValues.Length > 0)
            {
                EmitMetadataDictionary(writer.Write(", "), rule.MetadataValues);
            }

            writer.WriteLine(");");
        }

        foreach (var example in model.Examples
                    .GroupBy(
                         static example => new
                         {
                             example.Code,
                             Target = example.Target ?? string.Empty,
                             Message = example.Message ?? string.Empty,
                             Metadata = string.Join(
                                 "\u001F",
                                 example.MetadataValues.Select(
                                     static metadata => metadata.Key + "=" + (metadata.Value?.ToString() ?? string.Empty)
                                 )
                             )
                         }
                     )
                    .Select(static group => group.First())
                    .OrderBy(static example => example.Code, StringComparer.Ordinal)
                    .ThenBy(static example => example.Target, StringComparer.Ordinal))
        {
            writer
               .Write("builder.WithErrorExample(")
               .Write(ToStringLiteral(example.Code))
               .Write(", ")
               .Write(example.Target is null ? "null" : ToStringLiteral(example.Target))
               .Write(", ")
               .Write(example.Message is null ? "null" : ToStringLiteral(example.Message));

            if (example.MetadataValues.Length > 0)
            {
                EmitMetadataDictionary(writer.Write(", "), example.MetadataValues);
            }

            writer.WriteLine(");");
        }

        if (model.Rules.Length > 0 || model.Examples.Length > 0)
        {
            writer.WriteLine();
        }

        return writer;
    }

    private static CodeWriter EmitMetadataDictionary(
        CodeWriter writer,
        IEnumerable<MetadataValueModel> metadataValues
    )
    {
        var entries = string.Join(
            ", ",
            metadataValues.Select(
                static metadataValue =>
                    $"[{ToStringLiteral(metadataValue.Key)}] = {ToLiteral(metadataValue.Value)}"
            )
        );

        return writer
           .Write("new Dictionary<string, object?>(StringComparer.Ordinal) { ")
           .Write(entries)
           .Write(" }");
    }

    private static string? GetTypedHelperName(RuleCallModel rule) =>
        rule.Code switch
        {
            "EqualTo" => "WithEqualToError",
            "NotEqualTo" => "WithNotEqualToError",
            "GreaterThan" => "WithGreaterThanError",
            "GreaterThanOrEqualTo" => "WithGreaterThanOrEqualToError",
            "LessThan" => "WithLessThanError",
            "LessThanOrEqualTo" => "WithLessThanOrEqualToError",
            "InRange" => "WithInRangeError",
            "NotInRange" => "WithNotInRangeError",
            "ExclusiveRange" => "WithExclusiveRangeError",
            _ => null
        };

    private static string ToLiteral(object? value) =>
        value switch
        {
            null => "null",
            string stringValue => ToStringLiteral(stringValue),
            char charValue => "'" + EscapeChar(charValue) + "'",
            bool boolValue => boolValue ? "true" : "false",
            byte byteValue => byteValue.ToString(CultureInfo.InvariantCulture),
            sbyte sbyteValue => sbyteValue.ToString(CultureInfo.InvariantCulture),
            short shortValue => shortValue.ToString(CultureInfo.InvariantCulture),
            ushort ushortValue => ushortValue.ToString(CultureInfo.InvariantCulture),
            int intValue => intValue.ToString(CultureInfo.InvariantCulture),
            uint uintValue => uintValue.ToString(CultureInfo.InvariantCulture) + "U",
            long longValue => longValue.ToString(CultureInfo.InvariantCulture) + "L",
            ulong ulongValue => ulongValue.ToString(CultureInfo.InvariantCulture) + "UL",
            float floatValue => floatValue.ToString("R", CultureInfo.InvariantCulture) + "F",
            double doubleValue => doubleValue.ToString("R", CultureInfo.InvariantCulture) + "D",
            decimal decimalValue => decimalValue.ToString(CultureInfo.InvariantCulture) + "M",
            _ => ToStringLiteral(value.ToString() ?? string.Empty)
        };

    private static string ToStringLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2).Append('"');
        foreach (var c in value)
        {
            builder.Append(EscapeChar(c));
        }

        return builder.Append('"').ToString();
    }

    private static string EscapeChar(char value) =>
        value switch
        {
            '\\' => @"\\",
            '"' => "\\\"",
            '\'' => "\\'",
            '\0' => "\\0",
            '\a' => "\\a",
            '\b' => "\\b",
            '\f' => "\\f",
            '\n' => "\\n",
            '\r' => "\\r",
            '\t' => "\\t",
            '\v' => "\\v",
            _ => char.IsControl(value) ?
                "\\u" + ((int) value).ToString("x4", CultureInfo.InvariantCulture) :
                value.ToString()
        };
}
